  
# This is a basic workflow to help you get started with Actions

name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install NodeJS
      uses: actions/setup-node@v2-beta
      
    - name: Install Yarn
      uses: borales/actions-yarn@v2.0.0
      with:
        cmd: install
      
    - name: Install surge
      run: sudo npm install --global surge
      
    - name: Install related libraries
      run: sudo yarn add history@5 react-router-dom@6.0.0-beta.0 @wellyshen/use-web-animations
            
    - name: Build React App
      run: |
        unset CI
        yarn build
      
    - name: Deploy surge
      run: surge ./build kindest_project4a.surge.sh --token ${{secrets.SURGE_TOKEN}}
